### ISSUE TITLE
Can't query any ressource that have object as arguments

### ISSUE THREAD

**Issue by dragma** [Urigo/SOFA#1003]
Here is a part of my schema

```graphql
type Query {
  tag(where: TagWhereUniqueInput): Tag
}

type Tag {
  id: ID!

  name: String

  reports(skip: Int, take: Int): [Report!]!

  updatedAt: DateTime
  createdAt: DateTime
}

input TagWhereUniqueInput {
  id: ID
  name: String
}
```

here is the resolver of the tag Query 

```javascript
const tag = (_, { where }) => {
  console.log({ where });
  return prisma.tag.findUnique({ where });
};
```

Based on this, there is the swagger view  of the generated rest endpoint :
![image](https://user-images.githubusercontent.com/4975026/150543664-08817f91-d6c1-4d8e-96bd-e7b3c97e562f.png)

Now when I hit that endpoint with `http://localhost:4100/api/tag?where[id]=1`, here is the print of the `where` argument :
![image](https://user-images.githubusercontent.com/4975026/150544205-8662290e-c2b7-486a-92a6-865c3a6bf761.png)

Am I missing something ?

**Comment by avlan** [comment]
I'm facing the same issue when trying to query a resource with an object as an argument. I tracked it down to `URLSearchParams` in `pickParam` function not the query into an object. https://github.com/Urigo/SOFA/blob/6ecdc16bfc9b600823cd1681e7f50de755bbcedc/src/router.ts#L394 
Is this something that will be consider for future versions? I could help out with some pointers but I couldn't find an alternative to `URLSearchParams`.

Did you by chance found a workaround? @dragma

**Comment by nathanchapman** [comment]
Hey @Urigo is there a timeline on this one? This is preventing us entirely from adopting SOFA, since all of our queries accept a single `where` input object

**Comment by Urigo** [comment]
anyone is willing to try out sending a PR?
Maybe starting with a failing test?

**Comment by nathanchapman** [comment]
@Urigo I'll see if I can get a failing test set up to start!

**Comment by nathanchapman** [comment]
@Urigo sooo uhhhh... I wrote a test for it and it passed 🤣 
https://github.com/Urigo/SOFA/pull/1370

**Comment by nathanchapman** [comment]
I wonder if something else was going on with URL escaping on the double quotes 🤔 
Let me test that locally to confirm!
