### ISSUE TITLE
Generate descriptions for parameters in swagger

### ISSUE THREAD

**Issue by tatianafrank** [Urigo/SOFA#106]
Im generating swagger docs form my graphql schema but Im unsure how to add descriptions to request parameters in swagger via the graphql schema. I know how I would add the descriptions if I were adding them directly to swagger.yml but since Im auto-generating the swagger.yml using sofa/open api I need to add the descriptions into the graphql schema somehow. I tried using doc strings in the typedegs.gql file but that didn't work. Is there a way to do this?

**Comment by kamilkisiela** [comment]
[`v0.5.0`](https://github.com/Urigo/SOFA/releases/tag/v0.5.0)
