### ISSUE TITLE
Vulnerability in axios version

### ISSUE THREAD

**Issue by dmattia** [Urigo/SOFA#1063]
Axios version 0.21.2 or greater should be used to avoid the vulnerabilities mentioned in https://github.com/advisories/GHSA-cph5-m8f7-6c5x

If possible, using `^` on the axios version range would be appreciated

**Comment by ramonsnir** [comment]
@TrySound @ardatan You have Renovate enabled that actually dealt with this, but there wasn't a release in over a year so the dependency patches don't reach downstream.

**Comment by ardatan** [comment]
Fixed in 0.11.2
