### ISSUE TITLE
useSofa typings are not compatible with express

### ISSUE THREAD

**Issue by imwexpex** [Urigo/SOFA#1276]
Good day, looks like SOFA is not compatible with express (anymore?)

I'm receiving TS error:
 `Argument of type 'Router<DefaultSofaServerContext>' is not assignable to parameter of type 'Application<Record<string, any>>'.`

Minimum repro example: https://stackblitz.com/edit/graphql-dugtqd

**Comment by ardatan** [comment]
It seems a TS issue more than a functional issue. Until it gets fixed, you can add `as any` after `useSofa` call to make it work. Also if you use Yoga, you can try SOFA plugin which allows you to share the same setup between SOFA and Yoga;
https://the-guild.dev/graphql/yoga-server/docs/features/sofa-api

**Comment by imwexpex** [comment]
> It seems a TS issue more than a functional issue. Until it gets fixed, you can add `as any` after `useSofa` call to make it work. Also if you use Yoga, you can try SOFA plugin which allows you to share the same setup between SOFA and Yoga; https://the-guild.dev/graphql/yoga-server/docs/features/sofa-api

Hey! Thanks for a reply

1) Yoga was used just for example, on the main project, I'm using Apollo
2) Unfortunately, it's not only TS issue. It's functional also, can't set up SOFA to work with express. Do you have any working examples?

**Comment by ardatan** [comment]
It works with `as any`;
https://stackblitz.com/edit/graphql-uwzf28?file=index.ts
So you can check `/api/hello`.

**Comment by imwexpex** [comment]
> It works with `as any`; https://stackblitz.com/edit/graphql-uwzf28?file=index.ts So you can check `/api/hello`.

My bad, you're right. so looks like I should dig deeper into why in my project SOFA doesn't work

**Comment by ardatan** [comment]
Fixed in the latest version!
