### ISSUE TITLE
After updating sofa to 0.5.0 npm install failing

### ISSUE THREAD

**Issue by wtrocki** [Urigo/SOFA#129]
Not sure if that this is something with my env but..:

Steps to reproduce.

1. Add release to package json
2. npm install (finishes ok)
2. npm install again:

```
npm ERR! path test/node_modules/sofa-api
npm ERR! code EISGIT
sofa-api: Appears to be a git repo or submodule
```

**Comment by lukeandersen** [comment]
I had the same issue, seems the latest package on npm has a git directory in it. Try `rm -rf node_modules/sofa-api/.git` and that will fix it for now.

**Comment by wtrocki** [comment]
Yes. I have added postinstall script to do it.

**Comment by kamilkisiela** [comment]
`v0.5.1`
