### ISSUE TITLE
Error launching the app

### ISSUE THREAD

**Issue by kavya-medcharla** [Urigo/SOFA#1337]
I am a newbie working on GraphQL. When I try to expose GraphQL via Rest endpoints using SOFA as mentioned in the readme docs. However, I get the below error. Let me know what's missing.

**Error:** 
app.use('/api', useSofa({
                ^
TypeError: useSofa is not a function

<img width="1034" alt="Screenshot 2023-05-12 at 4 07 06 PM" src="https://github.com/Urigo/SOFA/assets/14984852/abae9194-11c4-4360-aa06-3e643a239abe">

**Comment by ardatan** [comment]
`const { useSofa } = require('sofa-api');`
It is a named export from `sofa-api`.

**Comment by kavya-medcharla** [comment]
So can't I use the way I used in line# 12? Also, I would like to test with a remotely hosted GraphQL API. Can you help me with pointers?

**Comment by ardatan** [comment]
Please share an initial example as a draft on CodeSandbox or StackBlitz, so let's continue there.
