### ISSUE TITLE
OpenAPI config missing since v0.17.0

### ISSUE THREAD

**Issue by KennethWussmann** [Urigo/SOFA#1338]
Hey,

With v0.17.0, SOFA now exposes the OpenAPI Spec and Swagger UI automatically. A great change in general and much appreciated.
But with that change, all configuration options of the previous `OpenAPI` function have been removed with seemingly no replacement. 

Previously one could document how an API is secured like this:
```typescript
const openApi = OpenAPI({
  schema,
  info: {
    title: 'My API',
    version: '1.0.0',
  },
  components: {
    securitySchemes: {
      bearerAuth: {
        type: 'http',
        scheme: 'bearer',
        bearerFormat: 'JWT',
      },
    },
  },
  security: [
    {
      bearerAuth: [],
    },
  ],
});

router.use(
  '/api',
  useSofa({
    basePath: '/api',
    schema,
    onRoute: (info) => {
      openApi.addRoute(info, {
        basePath: '/api',
      });
    },
  }),
);
```

The `OpenAPI` function still exists, but as `onRoute` was removed, there no longer is an option to configure this. 

With v0.17.1, we got `title` and `version` back as properties on `useSofa`, but all the other options of `OpenAPI`, like `components`, `security`, `servers`, etc., are still missing.

It would be great to either get `onRoute` back, so users who need these configuration options can continue using it like before or incorporate all `OpenAPI` configuration options into the `useSofa` function.

Let me know if I missed anything; the docs are, unfortunately, not very extensive on this topic.

Thank you!

**Comment by Bruno-Tome** [comment]
Hey, I've encountered the same problem. To work around this, my production environment is using 0.17.* and i have a local project which uses 0.16 which i can configure with tags and everything else, and then pass the spec with the attribute

`       swaggerUIOpts: {
          tryItOutEnabled: true,
          spec: spec as any,
        },`
        Where spec is the json that is generated from the Sofa 0.16

**Comment by ardatan** [comment]
Now you can define all extra properties for the generated OAS under `openAPI`.
See;
https://the-guild.dev/graphql/sofa-api/docs/recipes/open-api

**Comment by yuercl** [comment]
The document readme.md should be updated

**Comment by Urigo** [comment]
@yuercl could you help us and send a PR to the docs with the needed update?
