### ISSUE TITLE
Issue with base path in the Swagger UI

### ISSUE THREAD

**Issue by mirjanamihajlovic** [Urigo/SOFA#1339]
Hello,

In the feTS library that is used the base path was not prefixed in the Swagger UI. They have fixed the issue in https://github.com/ardatan/feTS/issues/164. Could you upgrade your dependency to use fets@0.1.5?

Thanks

**Comment by ardatan** [comment]
It is a ranged dependency. So you can basically recreate or update the lock file to get the latest;
https://github.com/Urigo/SOFA/blob/4b67dbb8980914f9f66ce6ea41b290fc1f120502/package.json#L47
