### ISSUE TITLE
How can use SOFA with Conditional Schema?

### ISSUE THREAD

**Issue by ggagosh** [Urigo/SOFA#1357]
Hey, Is there any way to use SOFA with [Conditional Schema](https://the-guild.dev/graphql/yoga-server/docs/features/schema#conditional-schema)?

**Comment by ardatan** [comment]
You can use Yoga as in the example then add SOFA plugin :) 
https://the-guild.dev/graphql/yoga-server/docs/features/sofa-api

**Comment by ggagosh** [comment]
> You can use Yoga as in the example then add SOFA plugin :) https://the-guild.dev/graphql/yoga-server/docs/features/sofa-api

Hey, there is no documentation on how to use this plugin with Conditional Schema. Based on the request.

**Comment by ardatan** [comment]
Maybe I am missing something here. Conditional schema is the configuration for Yoga. You configure the schema as in that section you shared then add the plugin as in the one I sent.

**Comment by ggagosh** [comment]
Ok, you are right, I just crate an issue for the wrong repo 😞 It's Yoga's error. I will close the issue. Thanks.

**Comment by ardatan** [comment]
What is the error you have?
You basically need to take this;
![image](https://github.com/Urigo/SOFA/assets/20847995/095bf28c-88d3-4bfc-b93e-0556af9ee87b)
And add the plugin like this;
![image](https://github.com/Urigo/SOFA/assets/20847995/3737caba-1fcb-4c33-8c1e-08fa3e530e72)

**Comment by ggagosh** [comment]
This is the [minimal reproduction](https://codesandbox.io/p/sandbox/dank-sea-qcsng7?file=%2Fsrc%2Fmain.ts%3A26%2C19), You can check logs. I also create an [issue](https://github.com/dotansimha/graphql-yoga/issues/2870) for Yoga.

Without a Sofa plugin, it works fine.

**Comment by devhoangkien** [comment]
i have a similar problem.: https://the-guild.dev/graphql/yoga-server/docs/features/sofa-api
```ts
const yoga = createYoga({
  landingPage: true,
  schema: createSchema({ typeDefs, resolvers }),
  plugins: [
    useSofa({
      basePath: '/api',
      swaggerUI: {
        endpoint: '/swagger'
      },
      openAPI: {
        info: {
          title: 'Bun Server REST API',
          version: '1.0.0',
          description: 'Bun Server REST API'

        }
      },
    })
  ]
},)
```
I call rest api on swagger successfully. but when calling on graphql, the following error is reported. Haven't called the server yet
```json
{
  "errors": [
    {
      "message": "Failed to fetch",
      "extensions": {
        "requestBody": {
          "query": "query MyQuery {\n  getPost(id: 1) {\n    content\n    title\n    id\n  }\n}",
          "operationName": "MyQuery"
        },
        "responseDetails": {}
      }
    }
  ]
}
```
but when I remove the plugin, graphql works normally
```ts
const yoga = createYoga({
  landingPage: true,
  schema: createSchema({ typeDefs, resolvers }),
  // plugins: [
  //   useSofa({
  //     basePath: '/api',
  //     swaggerUI: {
  //       endpoint: '/swagger'
  //     },
  //     openAPI: {
  //       info: {
  //         title: 'Bun Server REST API',
  //         version: '1.0.0',
  //         description: 'Bun Server REST API'

  //       }
  //     },
  //   })
  // ]
},)
```
```json
{
  "data": {
    "getPost": null
  }
}
``` 

i use bun 1.04
```ts
import { createSchema, createYoga } from 'graphql-yoga'
import { BunToText } from './utils/text-logs';
import { readFileSync } from 'node:fs'
import { resolvers } from './modules/app.resolvers';
import { useSofa } from '@graphql-yoga/plugin-sofa'


const typeDefs = readFileSync('./schema.graphql', 'utf8')

const yoga = createYoga({
  landingPage: true,
  schema: createSchema({ typeDefs, resolvers }),
  // plugins: [
  //   useSofa({
  //     basePath: '/api',
  //     swaggerUI: {
  //       endpoint: '/swagger'
  //     },
  //     openAPI: {
  //       info: {
  //         title: 'Bun Server REST API',
  //         version: '1.0.0',
  //         description: 'Bun Server REST API'

  //       }
  //     },
  //   })
  // ]
},)

const server = Bun.serve({
  fetch: yoga.fetch.bind(yoga),
  port: Bun.env.PORT || 8888,
  hostname: Bun.env.HOST || 'localhost',
  development: Bun.env.NODE_ENV !== 'production' ? true : false
});
console.info(BunToText)
console.info(
  `Server is running on ${new URL(
    yoga.graphqlEndpoint,
    `http://${server.hostname}:${server.port}`
  )}`
)
``` 
link github source: https://github.com/devhoangkien/bun-server-template.git
