### ISSUE TITLE
Broken NPM package

### ISSUE THREAD

**Issue by tunnckoCore** [Urigo/SOFA#1403]
Hey there.

Seems like the exports definitions are broken, the build system or whatever generates `cjs/src/index.js` and in the package.json everything is without the `src/` Putting it back fixes my problem of now been able to load it on graphql-yoga.

```json

  "main": "cjs/src/index.js",
  "module": "esm/src/index.js",
  "typings": "typings/src/index.d.ts",
  "typescript": {
    "definition": "typings/src/index.d.ts"
  },
  "type": "module",
  "exports": {
    ".": {
      "require": {
        "types": "./typings/src/index.d.cts",
        "default": "./cjs/src/index.js"
      },
      "import": {
        "types": "./typings/src/index.d.ts",
        "default": "./esm/src/index.js"
      },
      "default": {
        "types": "./typings/src/index.d.ts",
        "default": "./esm/src/index.js"
      }
    },
    "./package.json": "./package.json"
  }
```

**Comment by ardatan** [comment]
I don't see "src" when I checked the published package code here. Are you sure you are using the latest version?
https://www.npmjs.com/package/sofa-api?activeTab=code

**Comment by josephj** [comment]
Yea I got the same issue. Thank you @tunnckoCore for reporting this issue.

![CleanShot 2023-11-30 at 09 31 52@2x](https://github.com/Urigo/SOFA/assets/136648/0ad017a6-7dd3-456f-bb8f-806e20aa4b1a)

**Comment by josephj** [comment]
@ardatan 

> I don't see "src" when I checked the published package code here. Are you sure you are using the latest version?

![CleanShot 2023-11-30 at 12 34 19@2x](https://github.com/Urigo/SOFA/assets/136648/c2a155e2-8f2c-4263-9d29-d5b1d44f1e5e)

**Comment by josephj** [comment]
It works well after I use the fixed `0.18.0` version.

**Comment by Axum666** [comment]
also getting the same thing when trying to upgrade from 18.0 to 18.1

**Comment by taybin** [comment]
I'm running into this with 0.18.3.
