### ISSUE TITLE
How do I add headers to my response?

### ISSUE THREAD

**Issue by tatianafrank** [Urigo/SOFA#141]
Maybe this is obvious but where should I add custom headers to my response for a given endpoint?

**Comment by ardatan** [comment]
It depends on what you're trying to do. Could you explain more about your case?

**Comment by tatianafrank** [comment]
Im trying to set the "Access-Control-Allow-Origin" header on the response.

**Comment by ardatan** [comment]
You can write your own middleware or use `cors` npm package;
https://github.com/expressjs/cors

**Comment by tatianafrank** [comment]
Thanks for your quick replies! My question isnt abut cors but where I can add the logic. 
My code looks like this:
app.use(
    '/rest', 
    useSofa({
      schema,
      onRoute(info) {
        openApi.addRoute(info, {
          basePath: '/rest',
        });
      },
    })

Where in that code  could I add the logic/middlewear for headers?

**Comment by tatianafrank** [comment]
Figured it out:
``` app.use(
    '/rest', 
    (req, res, next) => {
      // render a regular page
      res.set({
        'Access-Control-Allow-Origin': '*',
      });
      next();
    },
    useSofa({
      schema,
      onRoute(info) {
        openApi.addRoute(info, {
          basePath: '/rest',
        });
      },
    }),
  );```
