### ISSUE TITLE
Generate descriptions for GraphQL parameters in swagger

### ISSUE THREAD

**Issue by tatianafrank** [Urigo/SOFA#147]
Using sofa-api@0.5.1 and still unable to add descriptions in swagger docs. I have typedefs.gql file and I'm trying to add descriptions to the fields and arguments using docstrings as documented here: https://www.apollographql.com/docs/graphql-tools/generate-schema/#descriptions--deprecations 
But the descriptions are not showing up.

**Comment by kamilkisiela** [comment]
v0.6.0
