### ISSUE TITLE
TypeError: value.map is not a function when using string array type

### ISSUE THREAD

**Issue by tatianafrank** [Urigo/SOFA#148]
One of my parameters is of type [String] and when this parameter is used in the REST request (passed in the url query), sofa api throws this error: `TypeError: value.map is not a function` I tried this on version 0.3.0, 0.5.0, 0.5.1 and ran into this issue on all.

**Comment by tatianafrank** [comment]
The issue was with how the array parameter was being passed in the URL.

**Comment by natschoman** [comment]
I have the same issue. 
Can I ask you how you solved it? 
How has the array parameter be passed in the url?
Tried 
```
?arrayInput=1,2,3
?arrayInput=[1,2,3]
?arrayInput[]=1&arrayInput[]=2&arrayInput[]=3
```
All with no success :(
