### ISSUE TITLE
Undefined/Null fields values

### ISSUE THREAD

**Issue by Elliot-Pitts** [Urigo/SOFA#185]
https://github.com/Urigo/SOFA/blob/master/src/parse.ts#L20

This needs to change to &&, as it's not catching undefined/null fields that are then attempted to parse throwing an error.

**Comment by Bran1304** [comment]
Any info on when the release is coming out?

**Comment by kamilkisiela** [comment]
[`sofa-api@0.6.1`](https://github.com/Urigo/SOFA/releases/tag/v0.6.1)
