### ISSUE TITLE
Parse fields recursively 

### ISSUE THREAD

**Issue by Elliot-Pitts** [Urigo/SOFA#186]
When an object is used in the request query, it's fields are not parsed into the correct GraphQL scalar type. This needs to be done recursively.

**Comment by kamilkisiela** [comment]
Could you create an example?

**Comment by aerskine** [comment]
@kamilkisiela a query field type of an array of enums would suffice as an example. Sofa doesn't seem to handle enums to begin with (feature request!:)), but my debugger reveals:

```
graphql_1.isEnumType(type)
false
graphql_1.isEnumType(type.ofType.ofType)
false
type.ofType.ofType
GraphQLNonNull {ofType: GraphQLEnumType}
type.ofType.ofType.ofType
GraphQLEnumType {name: "AdminRole", description: "Available admin roles", extensions: undefined, astNode: undefined, extensionASTNodes: undefined, …}
graphql_1.isEnumType(type.ofType.ofType.ofType)
true
```

the query in this case being:

```
extend type Query {
  """Retrieve the admin roles for a specific userId."""
  adminRoles(userId: String!): [AdminRole!]!
}
```

and `AdminRole` an enum.

**Comment by TrySound** [comment]
The problem was in nested `qs` params. Though we stepped away from them in favour of json params.
