### ISSUE TITLE
Support for Apollo dataSources

### ISSUE THREAD

**Issue by dagnello** [Urigo/SOFA#205]
I have an Apollo Server configured with dataSources, are there any plans to support Apollo Data sources in Sofa, apart from the workaround captured here: https://github.com/Urigo/SOFA/issues/58 ?

**Comment by ardatan** [comment]
Apollo DataSource is an object that is instantiated during the GraphQL request, and put inside the context. So this is what you can do already by yourself easily. I'm not sure if this should be considered as a workaround, because Apollo's data sources are not standard of GraphQL.
