### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by lnmunhoz** [Urigo/SOFA#21]
Hey Urigo,

First of all, thanks for this library. the concept is really cool, but...
I've just follow the simple configuration and tried to run, got this error:

```
RangeError: Maximum call stack size exceeded
```

This is the schema I am passing. It works fine with apollo-server:
```js
import { makeExecutableSchema } from "apollo-server"
import typeDefs from "./typeDefs"
import resolvers from "./resolvers"
import {
  isAuthDirective,
  hasScopeDirective,
  isAdminDirective,
} from "./directives"

export default makeExecutableSchema({
  typeDefs,
  resolvers,
  schemaDirectives: {
    isAuth: isAuthDirective,
    hasScope: hasScopeDirective,
    isAdmin: isAdminDirective,
  }
})
```

And the full stack trace:
```bash
RangeError: Maximum call stack size exceeded
    at resolveField (/foo/node_modules/sofa-api/src/operation.ts:278:22)
    at /foo/node_modules/sofa-api/src/operation.ts:218:16
    at Array.map (<anonymous>)
    at resolveSelectionSet (/foo/node_modules/sofa-api/src/operation.ts:217:39)
    at resolveField (/foo/node_modules/sofa-api/src/operation.ts:328:21)
    at /foo/node_modules/sofa-api/src/operation.ts:218:16
    at Array.map (<anonymous>)
    at resolveSelectionSet (/foo/node_modules/sofa-api/src/operation.ts:217:39)
    at resolveField (/foo/node_modules/sofa-api/src/operation.ts:328:21)
    at /foo/node_modules/sofa-api/src/operation.ts:218:16
    at Array.map (<anonymous>)
    at resolveSelectionSet (/foo/node_modules/sofa-api/src/operation.ts:217:39)
    at resolveField (/foo/node_modules/sofa-api/src/operation.ts:328:21)
    at /foo/node_modules/sofa-api/src/operation.ts:218:16
    at Array.map (<anonymous>)
    at resolveSelectionSet (/foo/node_modules/sofa-api/src/operation.ts:217:39)
```

Let me know what else I can provide to help you. 
Thank you!

**Comment by birkir** [comment]
I have the same thing, only when using OpenAPI.

```
openApi.addRoute(info, {
  basePath: '/api',
});
```

FYI: I have endless recursion in my schema, so something like this (totally valid of course)

```graphql
type A {
  b: B
}

type B {
  a: A
}
```

**Comment by lnmunhoz** [comment]
@birkir I do have recursion in my schema. But no, I've passed the same. 
@Urigo I will to create a reproduction and update here soon 👍

**Comment by birkir** [comment]
Here is my stack trace. It is definitely related to recursion of types.

My stacktrace:

```javascript
(node:9251) UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded
    at String.replace (<anonymous>)
    at module.exports (/Volumes/Data/Projects/prime/node_modules/no-case/no-case.js:32:6)
    at Object.module.exports (/Volumes/Data/Projects/prime/node_modules/camel-case/camel-case.js:12:16)
    at getArgumentName (/Volumes/Data/Projects/prime/node_modules/sofa-api/src/operation.ts:275:21)
    at /Volumes/Data/Projects/prime/node_modules/sofa-api/src/operation.ts:300:32
    at Array.map (<anonymous>)
    at resolveField (/Volumes/Data/Projects/prime/node_modules/sofa-api/src/operation.ts:297:23)
    at /Volumes/Data/Projects/prime/node_modules/sofa-api/src/operation.ts:218:16
    at Array.map (<anonymous>)
    at resolveSelectionSet (/Volumes/Data/Projects/prime/node_modules/sofa-api/src/operation.ts:217:39)
```

**Comment by verdverm** [comment]
I figured out a way to catch the issue, it's GraphQLNamedType cycle

here, put (https://github.com/Urigo/SOFA/blob/master/src/operation.ts#L142)
```
const visitedTypes: Record<string,bool> = {};
```

here, put (https://github.com/Urigo/SOFA/blob/master/src/operation.ts#L212)
```
let found = visitedTypes[type.name];
if (found) {
  return undefined;
}
visitedTypes[type.name] = true;
```

**Comment by verdverm** [comment]
getting closer, managed the recursion by memoizing types that had been seen, not recursing into another types field in the stack, and then unmemoizing as recursion unwinds. so...

```
query {
  a {
    b {
      a {     STOP HERE, don't recursively enter this field (actually stop in the previous b, when the a field is encountered
        b {
         ...
        }
      }
    }
 }
}
```

In actuality, this stopping point could be limited to some maximum depth.

**Comment by verdverm** [comment]
You can see the changes here: https://github.com/hofstadter-io/SOFA/pull/1

(note, the winston logger was removed because it was having issues with the format being undefined on import...)

**Comment by kamilkisiela** [comment]
Okay, should be fixed by #23 - I published it as `0.2.3-alpha.0`, could you guys try it out?

**Comment by birkir** [comment]
Works like a charm @kamilkisiela, thanks for the update!

I am shipping it with [prime](https://github.com/birkir/prime) this week!

**Comment by Urigo** [comment]
thank everyone for such detailed bug report!

@birkir that is awesome!

**Comment by verdverm** [comment]
@Urigo found another infinite recursion for `many-to-many` relations (and maybe some others):

edge case:
```
type A {
  bs: [B]
}

type B {
  as: [A]
}
```

https://github.com/hofstadter-io/SOFA/pull/2/files#diff-2317c71e030318850aad89d8379c14cbR220

**Comment by kamilkisiela** [comment]
@verdverm @Urigo The issue here is that if a type has only one field then we get:

```graphql
{
  b {
    a {
      b {
        a {...}
      }
    }
  }
}
```

If we want to omit the first circular reference then we get:

```graphql
{
  b {
    a {
      // empty :(
    }
  }
}
```

Since we can't execute such a query because of this empty block and all types has only one field then we should remove the first `b` and `a` too. Which leave us with an empty document.

I knew the limitation when I was fixing circular references but I assumed it's a very rare use-case when people has two types that uses themself through a single field.

Right now, I have no idea what could be the solution.

@verdverm Your solution turns an array into a single entity which is incorrect but maybe I don't see something, could you correct me?

**Comment by verdverm** [comment]
@kamilkisiela can you try my fork https://github.com/hofstadter-io/SOFA https://www.npmjs.com/package/@hofstadter-io/sofa-api

`"@hofstadter-io/sofa-api": "^0.3.1"`

the code is different, and has more/different fixes that were discovered after the initial changes.

WRT your last question, I think the changes here are missing the case to deal with sarrays, it's not actually changing the array into a single entity, but detecting that arrays and singles are the same type during memoization.

**Comment by kamilkisiela** [comment]
@verdverm our logic does the same, `getNamedType()` resolves with a named type, so it doesn't matter if it's list or a nullable node.

I also added `depthLimit` option (set to `1` by default) which enables to "cut off" the circular reference at `n` level deep.

I checked your code and the only difference is that you're passing `res` object into the context, which is something that could be done here too. Maybe you could create a Pull Request for that?

**Comment by kamilkisiela** [comment]
Actually, we pass `res` too

**Comment by mundane140** [comment]
Hi,
I want to use SOFA to generate a rest API. What kind of things should I avoid when putting together a schema inorder to circumvent this issue?
I would totally understand if you feel I am off topic, but I don't know where else to go and I certainly don't want a "Maximum call stack size exceeded".
