### ISSUE TITLE
Integrating Sofa with Postgraphile

### ISSUE THREAD

**Issue by Kennycheng35** [Urigo/SOFA#224]
So, I believe @jnevin already messaged you before, but this is the problem we are currently facing.

We want to set up Sofa with a Postgraphile server. Postgraphile is a middleware that automatically generates a GraphQL schema from a Postgres database. So the end goal is to automatically create a GraphQL schema and query endpoint with automatically generated REST endpoints on top.

Here is a sample code below. 

```
const express = require("express");
const {postgraphile,createPostGraphileSchema, withPostGraphileContext} = require('postgraphile');
const {useSofa} = require('sofa-api');
const listRESTEndpoints = require('express-list-endpoints');
const app = express();

createPostGraphileSchema("postgres://admin:ev-udp@localhost:5432/ev_udp_db",'public', { dynamicJSON: true }).then(schema=>{
    console.log('schema', JSON.stringify(schema));
    
    app.use('/rest', useSofa({ schema }));
    app.use('/graphql',
        postgraphile(
            "postgres://admin:ev-udp@localhost:5432/ev_udp_db",
            "public",
            {
                watchPg:true,
                graphiql:true,
                enhanceGraphiql: true,
            }
        ),
    )
    console.log(listRESTEndpoints(app));
    app.listen(3005);
})
.catch(err=>console.log(err));
```
We created a schema with a Postgraphile function and we want to use that schema to power the Sofa middleware. 

The endpoints seem to generate alright, but when you actually try and make requests to those endpoints, you get this error.

`
TypeError: Int cannot represent non-integer value: undefined
    at GraphQLScalarType.serializeInt [as serialize] (/Users/kennycheng/dev/udp/ugroup-api/node_modules/graphql/type/scalars.js:43:11)
    at resolveVariable (/Users/kennycheng/dev/udp/ugroup-api/node_modules/sofa-api/dist/parse.js:24:30)
    at Object.parseVariable (/Users/kennycheng/dev/udp/ugroup-api/node_modules/sofa-api/dist/parse.js:6:16)
    at /Users/kennycheng/dev/udp/ugroup-api/node_modules/sofa-api/dist/express.js:165:35
    at Array.reduce (<anonymous>)
    at /Users/kennycheng/dev/udp/ugroup-api/node_modules/sofa-api/dist/express.js:163:47
    at Generator.next (<anonymous>)
    at /Users/kennycheng/dev/udp/ugroup-api/node_modules/sofa-api/dist/express.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/kennycheng/dev/udp/ugroup-api/node_modules/sofa-api/dist/express.js:4:12)
`

Not entirely sure how the context and execute functions within Sofa. Could it possibly be a problem with those?

**Comment by ardatan** [comment]
SOFA needs to be passed `GraphQLSchema` and context if you need. So as I see in Postgraphile docs, you can get context using `withPostGraphileContext`.
https://www.graphile.org/postgraphile/usage-schema/

Could you please share more details such as what was the URL of the request, what was the request body?

**Comment by ardatan** [comment]
Feel free to open a new issue if the problem still persists.
