### ISSUE TITLE
Cannot use SOFA generated endpoint with Axios POST

### ISSUE THREAD

**Issue by seancwalsh** [Urigo/SOFA#277]
I am running into CORS issues when trying to make `POST` request from the client using Axios - `GET` requests work fine.

I have no problem when making request from Postman. Setting header to `"Content-Type": "application/json"`. Resolver is executed as expected and data is returned.

When trying to replicate request in Axios, this error is thrown:
![image](https://user-images.githubusercontent.com/39013096/73760127-9e409600-4775-11ea-8a19-8e2b398674aa.png)

Preflight check is sent to server:
![image](https://user-images.githubusercontent.com/39013096/73760230-bca69180-4775-11ea-924e-5076a9725653.png)

Here's some middleware used on the server incase this helps:
![image](https://user-images.githubusercontent.com/39013096/73760532-21fa8280-4776-11ea-8f9c-c5be2afc72f4.png)

Please let me know if I can provide more details.

Thanks in advance!

**Comment by ardatan** [comment]
This is not a SOFA-specific issue. SOFA is an express middleware that handles specific routes in specific HTTP methods.
So, you need to handle CORS by yourself in your express application. 
https://expressjs.com/en/resources/middleware/cors.html

**Comment by seancwalsh** [comment]
My apologies - I wasn't sure the SOFA middleware was manipulating headers in some way.
