### ISSUE TITLE
ID Scalar type appears as type object in Swagger

### ISSUE THREAD

**Issue by seancwalsh** [Urigo/SOFA#279]
When setting ID as input type, swagger generates object type, which is a little confusing when looking at the docs. Though, not a big problem.

![image](https://user-images.githubusercontent.com/39013096/74146757-7ab09c00-4c0a-11ea-8146-5d9476703492.png)

![image](https://user-images.githubusercontent.com/39013096/74146614-26a5b780-4c0a-11ea-8b01-42e8edecc578.png)

![image](https://user-images.githubusercontent.com/39013096/74146647-3f15d200-4c0a-11ea-9c07-9b1d463c734e.png)

**Comment by seancwalsh** [comment]
Thanks @ardatan :)

**Comment by kamilkisiela** [comment]
[`sofa-api@0.6.1`](https://github.com/Urigo/SOFA/releases/tag/v0.6.1)
