### ISSUE TITLE
Authorization on REST endponts

### ISSUE THREAD

**Issue by samosbor** [Urigo/SOFA#32]
Is there any way to add authorization to the REST endpoints generated by my graphql queries?

**Comment by valerio-battaglia** [comment]
Here you go https://blog.pusher.com/handling-authentication-in-graphql/

**Comment by Urigo** [comment]
Any reason why the existing authentication of the GraphQL endpoint won't be enough?

**Comment by ardatan** [comment]
Authentication can be done in GraphQL Side using context. See our examples and blog post related to this scenerio.
https://medium.com/the-guild/authentication-and-authorization-in-graphql-and-how-graphql-modules-can-help-fadc1ee5b0c2
