### ISSUE TITLE
Return errors as JSON

### ISSUE THREAD

**Issue by valerio-battaglia** [Urigo/SOFA#33]
How can I setup Sofa so that when my queries `throw`s error they are formatted as `JSON` instead of `HTML`?

**Comment by Urigo** [comment]
Can you create a small repo that does that, maybe with a test?
I can work on that then

**Comment by valerio-battaglia** [comment]
Here you can find the code: https://typegraphql.ml/docs/authorization.html#recipes
The problem is that if JWT throws any error, SOFA would spit out an HTML file instead of a JSON.

**Comment by antitoine** [comment]
Same problem for me. I was wondering if it would not be possible to rewrite the execution function ('execute' option when creating sofa router, adding a simple try/catch), but we have no way to call back the initial sofa execution function.

**Comment by kamilkisiela** [comment]
Related #44 #45

**Comment by kamilkisiela** [comment]
Released as [`v0.4.0`](https://github.com/Urigo/SOFA/releases/tag/v0.4.0)

**Comment by kamilkisiela** [comment]
Closing but let us know if there's still an issue
