### ISSUE TITLE
Open API Swagger docs

### ISSUE THREAD

**Issue by tatianafrank** [Urigo/SOFA#355]
Is there a way to add regular text to the swagger docs in addition to the automatically generated routes info? We want to add some general documentation/info to the page but not sure how.

**Comment by jozan** [comment]
If there is a way I would like to know as well. :)

**Comment by kamilkisiela** [comment]
@tatianafrank @jozan 

You can access OpenAPI / Swagger object like this:

```javascript
const openApi = OpenAPI({
  schema,
  info: {
    title: 'Example API',
    version: '3.0.0',
  },
});

const HERE = openApi.get();
```

and mutate the `HERE` object.

We could provide a way to add some data at `OpenAPI.addRoute` level if you prefer.

**Comment by tatianafrank** [comment]
thanks!
