### ISSUE TITLE
Request variables not passed to GraphQL mutation

### ISSUE THREAD

**Issue by aaronhayes** [Urigo/SOFA#36]
I cannot seem to get mutations working; request variables are always null. See the example below.  

```JavaScript
// Type definitions define the "shape" of your data and specify
// which ways the data can be fetched from the GraphQL server.
const typeDefs = gql`
  # Comments in GraphQL are defined with the hash (#) symbol.

  # This "Book" type can be used in other type declarations.
  type Book {
    title: String
    author: String
  }

  # The "Query" type is the root of all GraphQL queries.
  # (A "Mutation" type will be covered later on.)
  type Query {
    books: [Book]
  }

  type Mutation {
    create_book(title: String!, author: String!): Book
  }
`;

// Resolvers define the technique for fetching the types in the
// schema.  We'll retrieve books from the "books" array above.
const resolvers = {
  Query: {
    books: () => books
  },
  Mutation: {
    create_book: (_: any, { title, author }: any) => {
      books.push({ title, author });
      return { title, author };
    }
  }
```
```
Error: Variable "$title" of required type "String!" was not provided.

GraphQL request (1:29)
1: mutation createBookMutation($title: String!, $author: String!) {
                               ^
2:   create_book(title: $title, author: $author) {
,Variable "$author" of required type "String!" was not provide
```
In the example above, both `title` and `author` are always null when using the sofa rest api.

[Full Repeatable Example Repo](https://github.com/aaronhayes/graphql-rest-typescript-example)

**Comment by oalcantar** [comment]
I'm getting the same error too, @aaronhayes did you found a solution to this issue?

**Comment by aaronhayes** [comment]
@oalcantar not yet. I haven' dug into SOFA's code which is where I believe the bug lives.

**Comment by oalcantar** [comment]
looking into the SOFA's code example I realized that they use the package `body-parser`, the `body-parse` is applied to express like this:

`app.use(bodyParser.json());`

I applied this changes in my code and now it works, I hope this works for you too

SOFA's code example
https://github.com/Urigo/SOFA/blob/master/example/index.ts#L19

@aaronhayes

**Comment by aaronhayes** [comment]
Yep that's the solution.
