### ISSUE TITLE
Error when using Rest DataSources

### ISSUE THREAD

**Issue by Rykuno** [Urigo/SOFA#404]
When using Apollo Server's, sofa-api returns an error something along the lines of 
`"{"message": "Cannot read property '<dataSource>' of undefined}".
`
I presume its because we only pass the executable schema to the sofa-api middleware. Whereas when initializing an apollo server we include the datasouces outside the executable schema
```
const server = new ApolloServer({
  schema,
  dataSources: () => {
    return {
      moviesAPI: new MoviesAPI(),
   };
 }
});
```

Is anyone privy to a way to get datasources working within the sofa-api? 

```
    "apollo-datasource-rest": "^0.7.0",
    "apollo-server-express": "^2.6.7",
    "sofa-api": "^0.7.0",
```

**Comment by ardatan** [comment]
You can add datasources to the context manually.
```
context: () => ({ 
    dataSources: {
        moviesAPI: new MoviesAPI(),
     }
})
```

**Comment by Rykuno** [comment]
> You can add datasources to the context manually.
> 
> ```
> context: () => ({ 
>     dataSources: {
>         moviesAPI: new MoviesAPI(),
>      }
> })
> ```

This works. Thanks!

**Comment by ardatan** [comment]
@Rykuno Data sources are not part of GraphQL Spec and they are Apollo specific so you have to handle by yourself. Also see;
https://github.com/Urigo/SOFA/issues/214#issue-533584788
