### ISSUE TITLE
OpenAPI does not have a way to document required headers

### ISSUE THREAD

**Issue by awildeep** [Urigo/SOFA#477]
I am currently using type-graphql and Sofa together, however when I attempt to run the OpenAPI doc, I can not seem to find a way to annotate that I need a given header on a request.  For example a JWT token requirement on an endpoint via the authorization header.

**Comment by ruicore** [comment]
have you solved it? I have the same question too.

**Comment by m1m1s1ku** [comment]
You can by patching the OpenAPI generated path definition (adding the parameters)

```js
for(const path of Object.keys(router.openAPIDocument.paths)) {
  const pathDefinition = router.openAPIDocument.paths[path];
  const pathMethods = Object.keys(pathDefinition);
  for(const method of pathMethods) {
    const methodDefinition = pathDefinition[method];
    methodDefinition.parameters?.push(
      {
        name: 'x-header-name', in: 'header', required: true
      }
    );
  }
}
```

(router in this context is the returnType of `useSofa`)
