### ISSUE TITLE
Plan to support Apollo federation

### ISSUE THREAD

**Issue by aaronleesmith** [Urigo/SOFA#48]
Can Sofa-api be used out of the box with Apollo federation? I would like to try this out without using schema stitching (which is deprecated) and would love to know the thoughts of the library authors.

**Comment by ardatan** [comment]
SOFA is independent from any framework and library. You only need to provide a valid `GraphQLSchema`. 
https://github.com/apollographql/federation-demo/blob/00f5119040e1b0ffba5adf220a585a7b83b1fbd4/gateway.js#L14
As you can see here in Apollo's example, we also need custom execution phase as documented here;
https://sofa-api.com/docs/api/execute

So if we combine these two;
```ts
  const { schema, executor } = await gateway.load();
  app.use(
  useSofa({
    schema,
    execute: executor,
  })
```

We can use SOFA with federation like above.
