### ISSUE TITLE
Question re: Apollo / GraphQL-Yoga

### ISSUE THREAD

**Issue by kleydon** [Urigo/SOFA#52]
Hi,

I'm an interaction designer ramping up on modern web development approaches, and Sofa struck me as mind-bogglingly useful. Thanks for unleashing this upon the world! 
(Additionally - my girlfriend and I both love the project's website.)

One thing I'm struggling with, as a relative newbie, is how to use Sofa with servers that may _implicitly_ or _currently_ be based on express, but are not _intrinsically_ based on express; i.e. Apollo and GraphQL-Yoga.

I've tried to integrate Sofa with GraphGL-Yoga on my own, and tested github examples that attempt to integrate Sofa, but am so far striking out.

Do you have any recommendations, or can you point to any examples that you know to be working?

Thanks again for creating this project.

**Comment by Urigo** [comment]
@kleydon can you publish your try?  would be easier to understand where the error might be

**Comment by kleydon** [comment]
Sure @Urigo  - thanks.

My server code is below; my repo (based on alan345's "naperg"), is posted at https://github.com/kleydon/naperg-sofa-test, in the server directory.

Sofa's documentation presumes an express-based server, but I'm working with GraphGL-Yoga (Apollo-based) server. My understanding is that Apollo _can_ be (and by default is) express-based, but that it doesn't _have to_ be - so I've been trying to take an express-agnostic approach (if that is even possible?) 

With my server running, I can successfully query users' ids via the GraphIQL playground (without any authentication headers), using:
```
{
  users {
    id
  }
}
```
...so I know that the server is running, and that users can be requested without authentication.

However, when I attempt to access my server's Sofa-generated rest endpoints (using Postman, with no headers or body) via any of the following requests, none yields a rest API.

If you have any tips or suggestions - I'm all ears!

GET  http://localhost:4000/rest/users
Cannot GET /rest/users

GET  http://localhost:4000/rest/user
{"message":"Variable \"$where\" of required type \"UserWhereUniqueInput!\" was not provided.","locations":[{"line":1,"column":17}]}

GET http://localhost:4000/rest/user/cjy7vluy3000v08893ud4i5g2
Cannot GET /rest/user/cjy7vluy3000v08893ud4i5g2 <-- A known, legitemate user id

GET http://localhost:4000/rest/user/id/cjy7vluy3000v08893ud4i5g2
Cannot GET /rest/user/id/cjy7vluy3000v08893ud4i5g2 <-- A known, legitemate user id

POST http://localhost:4000/rest/user
Cannot POST /user

POST http://localhost:4000/rest/users
Cannot POST /rest/users


```
//Server
//---------------------------------------------------------------
const { GraphQLServer } = require('graphql-yoga')
const { Prisma } = require('prisma-binding')
const resolvers = require('./src/resolvers')

//For Sofa:
const { useSofa } = require('sofa-api')
const { importSchema } = require('graphql-import')
const { makeExecutableSchema } = require('graphql-tools')

const prisma = new Prisma({
    typeDefs: 'generated-schema.graphql',
    endpoint: 'http://localhost:4466/naperg/dev'})

const server = new GraphQLServer({
  typeDefs: 'schema.graphql',
  resolvers,
  context: req => ({
    ...req,
    db: prisma
  })
})

//Enabling Sofa...
const typeDefs = importSchema('./schema.graphql')
const schema = makeExecutableSchema({ typeDefs, resolvers: resolvers })
//Try with/without express
//server.use('/rest', useSofa({ schema }));
server.express.use('/rest', useSofa({ schema }));

const options = {
    // playground: null, // Dissable playground endpoint,
}
server.start(options, () => { console.log('Server is running on http://localhost:4000') })

**Comment by kleydon** [comment]
@Urigo Never-mind; figured it out. Wasn't using context properly...

```
    useSofa({
        schema,
        async context({ req }) {
            return {
              request: req,
              prisma,
            };
        });
```

**Comment by Urigo** [comment]
thanks for the working example!

**Comment by Purus** [comment]
Can you please share that working version of your repo with Graphql-Yoga?

**Comment by kleydon** [comment]
Hi @Purus ,

Here are the key bits (below). 

Adding the request to context was the thing I struggled with. Its also worth noting that there is a `request` in the `request` (`request.request`), which SOFA/OpenAPI calls `req` instead (`request.req`).

```
//Create server
const server = new GraphQLServer({
  schema,
  middlewares: [permissions],
  context: request => {
    return {
      ...request,
      photon,
    }
  },
})

// Sofa, OpenAPI, Swagger
const openApi = OpenAPI({
  schema,
  info: {
    title: "API Docs...",
    version: "1.0.0"
  }
});
server.express.use(
  restBasePath,
  useSofa({
      schema,
      context: (request: any) => {

        //Sofa (or OpenAPI? or Swagger?) says "req:" and "res:";
        // Prisma says "request:", and "response:"
        //switch to "request:" and "response:" for interoperability
        // NOTE: Do this at the end of the chain of express modules,
        // in case other express modules expect "req"/"res"
        if (request.req) {
          request = replaceKey(request, 'req', 'request');
        }         
        if (request.res) {
          request = replaceKey(request, 'res', 'response');
        }

        return {
          ...request,
          photon,
        }
      },
      depthLimit: 3,
      onRoute(info:any) {
          openApi.addRoute(info, {
          basePath: restBasePath
        });
      }
    }));
  server.express.use("/rest-docs", swaggerUi.serve, swaggerUi.setup(openApi.get()));
}
```

**Comment by reubano** [comment]
I'm using KeystoneJs and am getting the same error. The contexts that @kleydon provided don't help either.

**Comment by joshuaja** [comment]
@reubano - did you ever figure this out for KeystoneJS? I'm running into the same error.

**Comment by reubano** [comment]
@joshuaja I don't recall. I also haven't touched KeystoneJs in years so I no longer have a need to figure it out.
