### ISSUE TITLE
Scalars as return types

### ISSUE THREAD

**Issue by wtrocki** [Urigo/SOFA#54]
I have made quick sample app that uses following schema:

```graphql
type Query {
   test: String
} 
```

however this doesn't seem to be exposing api/test endpoint. 
Getting 404. 

Maybe it is worth to mention that API does not support Scalars as return types as they cannot be put into json.

**Comment by kamilkisiela** [comment]
I think it does and here's the proof #57. Could you maybe share more and if it doesn't work for you, maybe create a reproduction?

**Comment by wtrocki** [comment]
@kamilkisiela My bad. My application expected JSON output were in fact returned body simply string.
