### ISSUE TITLE
using sofa with @nexus/schema ?

### ISSUE THREAD

**Issue by johhansantana** [Urigo/SOFA#548]
I'm using 

```typescript
import { makeSchema } from "@nexus/schema";

export const schema = makeSchema({
  types: [
    Query,
    Mutation,
    ...
  ]
]);
```

but when I run I get a bunch of errors related to typescript:
![image](https://user-images.githubusercontent.com/9933887/93125153-b62bb100-f698-11ea-9670-36d73935cb45.png)

**Comment by johhansantana** [comment]
nvm, was able to get it running with these scripts:

```
"start": "ts-node --transpile-only ./src/sofa",
"dev": "ts-node-dev --no-notify --respawn --transpileOnly ./src/sofa",
```

**Comment by LRipi** [comment]
Just in case you want an example, I've made one here: https://github.com/LRipi/sofa-graphql
