### ISSUE TITLE
Integrating SOFA with Apollo

### ISSUE THREAD

**Issue by DurandMathieu** [Urigo/SOFA#58]
Hi,

I'm trying to integrate SOFA with a simple ApolloServer. I saw issue #52 which seems similar, but the linked repository is not available anymore. I was able to create a basic setup with Swagger using the example from SOFA, and both my swagger-ui and Graphql Playground are working.

If I understand correctly, the SOFA implementation doesn't make a call to my ApolloServer, but instead it creates its own graphql implementation underneat using the same schema. Correct?

My problem is that in my resolvers, I use Apollo dataSources, which are not defined when going through SOFA. I tried to use the "context" configuration of SOFA to inject them, but it's not that easy, because an Apollo's dataSource need to be initialized, and this initialization is performed by Apollo for each request. I could probably make it work using custom code and looking at how the Apollo initialization works, but I'm just trying to see if I'm missing something and if maybe the answer is more obvious.

Here is my demo repository:
https://github.com/DurandMathieu/demo-graphql-rest

The interesting files are:
https://github.com/DurandMathieu/demo-graphql-rest/blob/master/src/index.ts
https://github.com/DurandMathieu/demo-graphql-rest/blob/master/src/dog/resolvers.ts

**Comment by ardatan** [comment]
You can use `context` field to pass `dataSources` like below;
```ts
app.use(
  useSofa({
    schema,
    context: ({ req }) => ({
          req,
          dataSources: getDataSources(),
    })
    onRoute(info: any) {
      openApi.addRoute(info, {
        basePath: ""
      });
    }
  })
);
```
Isn't this working?

**Comment by DurandMathieu** [comment]
The problem is that the data sources are initialized by apollo (each datasource has an initialize method which is called by the apollo request handler). Doing it the way you propose would create the datasources without initializing them. Like I said, I could probably initialize them manually looking at the apollo code and doing the same thing, but bypassing Apollo completely doesn't seem like a good idea. There may be some differences between my Apollo graphql endpoint and the SOFA rest endpoints calling the resolvers directly. 

What I'm looking for is a way to configure SOFA to delegate the graphql resolution to an existing server like Apollo. How hard would that be? Could SOFA just call the /graphql apollo endpoint which is on the same express server it's hosted on? I tried providing an execute method to SOFA and use ApolloClient and Link to dispatch the executing to http://localhost:4000/graphql, but I was unsuccessful. Do you see another way?

**Comment by ardatan** [comment]
@DurandMathieu If you want to initialize them as same as Apollo does;
```ts
import { InMemoryLRUCache } from 'apollo-server-caching';
const cache = new InMemoryLRUCache(); // In order to share cache with Apollo Server
const app = express();
const options = {
  dataSources: getDataSources,
  schema,
  cache
};
const server = new ApolloServer(options);
server.applyMiddleware({ app });
app.use(
  useSofa({
    schema,
    context: ({ req }) => {
        const dataSources = getDataSources();
        const context = { req, dataSources };
        // This is what Apollo does internally
        dataSources.forEach(dataSource => dataSource.initialize({ cache, context }));
        return context;
    },
    onRoute(info: any) {
      openApi.addRoute(info, {
        basePath: ""
      });
    }
  })
);
```
@kamilkisiela We can add this to recipes. What do you think?

**Comment by DurandMathieu** [comment]
I'm ok with your solution. My only concern is that we reuse internal configuration and behavior from the ApolloServer, which means that if for some reason they change something in the future, upgrading version might break my implementation. But since it's a very small bit of code, it's not that big of a deal.

Here is a small fix to your code, for anyone searching for the same solution. The dataSources returned is not an array, but an object, so the forEach doesn't work.
```
context: ({ req }) => {
      const dataSources = getDataSources() as any;
      const context = { req, dataSources };
      // This is what Apollo does internally
      for (const dataSource of Object.values(dataSources) as any) {
        if (dataSource.initialize) {
          dataSource.initialize({context, cache});
        }
      }
      return context;
    },
```
