### ISSUE TITLE
mapping generated api to graphql resolver

### ISSUE THREAD

**Issue by Sagar505** [Urigo/SOFA#59]
Below is the graphql schema -
```
var schema = buildSchema(`
    type Query {
        rollDice(numDice: Int!, numSides: Int): [Int]
      }
`);
var root = {
  rolldice: function ({numDice, numSides}) {
    var output = [];
    for (var i = 0; i < numDice; i++) {
      output.push(1 + Math.floor(Math.random() * (numSides || 6)));
    }
    return output;
  }
};
```
Sofa generated the Rest API as api/roll-dice and not api/rolldice ? Why ?
The API generated by Sofa did not map to grapghQL resolver function rolldice. How to make Sofa generated API to call graphql resolver function when the api/rolldice is called ?

**Comment by ardatan** [comment]
You can change `rollDice` to `rolldice` in GraphQL Schema.

**Comment by ardatan** [comment]
Please feel free to open a new issue if the problem persists.
