### ISSUE TITLE
swagger.yml generated by openAPI displays error in swagger editor

### ISSUE THREAD

**Issue by Sagar505** [Urigo/SOFA#60]
For API documentation, swagger.yml file is generated using below function - 
```
app.use(
    '/api',
    useSofa({
      schema,
      onRoute(info) {
        openApi.addRoute(info, {
          basePath: '/api',
        });
      },
    })
  );
```
The YAML file generated, when loaded in swagger editor displays error  as below -
```
Structural error at paths./api/hello.get.responses.200
should have required property 'description'
missingProperty: description
Jump to line 5
Structural error at paths./api/hello.get.requestBody
should be object
Jump to line 6
Structural error at paths./api/roll-dice.get.responses.200
should have required property 'description'
missingProperty: description
Jump to line 6
Semantic error at paths./api/hello.get.requestBody
GET operations cannot have a requestBody.
Jump to line 6
```
The same error is displayed for yaml at https://raw.githubusercontent.com/DurandMathieu/demo-graphql-rest/master/swagger.yml 

How to generate yaml file with no error ?

**Comment by ardatan** [comment]
@Sagar505 When I run your project locally, I don't see any errors. Also I didn't see any errors in the swagger file you sent. Does the error persist?

**Comment by Sagar505** [comment]
If the yaml generated is pasted in online swagger editor, error is displayed. Please paste the yaml file at https://editor.swagger.io/?_ga=2.212505746.701919280.1567689315-783988197.1562674380

**Comment by kamilkisiela** [comment]
[`v0.5.0`](https://github.com/Urigo/SOFA/releases/tag/v0.5.0)
