### ISSUE TITLE
feat: customizing paths for more restful approach

### ISSUE THREAD

**Issue by basselalaraaj** [Urigo/SOFA#608]
### GraphQL Schema
```graphql
type Query {
    getCart(id: ID!): Cart
}

type Mutation {
    createCart(cartInput: cartInput!): Cart
}

```
### Generated REST paths
```shell
GET  /api/get-cart/{id}
POST /api/create-cart/{id}
```
### RESTful paths
```shell
GET  /api/cart/{id}
POST /api/cart
```
### Example of possible implementation
```typescript
api.use(
  '/api',
  sofa({
    schema,
    path: {
      'Query.getCart': 'cart/{id}',
      'Mutation.createCart': 'cart',
    },
  })
);
```

**Comment by basselalaraaj** [comment]
@Urigo Any news about this feature request?

**Comment by LRipi** [comment]
@basselalaraaj He never answers on my message on Github's mentions nor twitter pm...

**Comment by TrySound** [comment]
Hi. We already have method customisation. @LRipi requested status customisation. We can provide something more universal like this
```js
useSofa({
  ...,
  routes: {
    'Query.getCart': {
      method: 'POST',
      path: '/cart/:id',
      responseStatus: 200
    }
  }
})
```

**Comment by kmensink95** [comment]
How can I use this in my project?

**Comment by kmensink95** [comment]
Thank you for your help it works perfect! My last question I hope you have some time to help me. I want to have tags in my swagger.json file for every endpoint. Is there a way to generate this in my openAPI? I can't find anything in the documentation for this issue.
