### ISSUE TITLE
Integration with Type-Graphql

### ISSUE THREAD

**Issue by thewasta** [Urigo/SOFA#666]

**Comment by thewasta** [comment]
Forgive I posted the issue without description.

I'm new with graphql and currently working with Type-Graphql and tried to integrate with sofa-api, but can't figure out
with type-graphql I use `await buildSchema({resolvers: [PingResolver]})` but this is not working with sofa-api, most of docs use makeExecutableSchema can't use it (I don't know how to use it, if I have a class PingResolver).

Anyone knows how? Should I read docs graphql-tools to integrate it?

**Comment by ardatan** [comment]
@thewasta The schema TypeGraphQL gives you can be used with Sofa. Sofa only expects GraphQLSchema object so it doesn't matter how you create it.

**Comment by thewasta** [comment]
Thanks. I was doing wrong! 👍
