### ISSUE TITLE
Rest nullable argument passes 0 instead of null when left out of request

### ISSUE THREAD

**Issue by tatianafrank** [Urigo/SOFA#67]
I have a graphql query resolver that accepts nullable arguments. One of those arguments is of type int and when I make a rest call to the endpoint without that argument, it passes 0 instead of null.

**Comment by ardatan** [comment]
@tatianafrank Could you share a reproduction?
I tried to reproduce it but it works well
https://github.com/ardatan/sofa-nullable-repro

**Comment by tatianafrank** [comment]
@ardatan thanks for looking into this! Since you weren't able to reproduce I did some more digging and found the cause of the issue and it's not an issue with Sofa so I will close the ticket.
