### ISSUE TITLE
OpenApi Swagger tags generated (Grouping operation)

### ISSUE THREAD

**Issue by kmensink95** [Urigo/SOFA#763]
**Is there a possibility to give tags to the endpoints?** 

I would like the documentation to be neatly ordered and that not all endpoints are under the default heading. I don't want to write it myself, I want it to be automatically generated for my customers.

**Comment by amenonts** [comment]
I recently used this framework to open up rest API endpoints on top of the graphQL and definitely felt this grouping option would be a big plus. Please do consider this enhancement.

**Comment by ardatan** [comment]
We'd love to accept PRs if someone wants to work on this.

**Comment by ardatan** [comment]
Fixed by https://github.com/Urigo/SOFA/pull/1114
